### ISSUE TITLE
[CI] consola syntax error on nullish coalescing operator

### ISSUE THREAD

**Issue by jacobgkau** [system76/docs#1206]
After doing a fresh clone, then running `npm ci` and `npm start`, I'm getting an error for the nullish coalescing operator present in the version of consola (a dependency of nuxt-cli) being used:

```
jacob@serw13:~/Work/support-docs/system76/docs$ npm start

> @system76/docs@1.0.0 start
> nuxt dev

/home/jacob/Work/support-docs/system76/docs/node_modules/@nuxt/utils/node_modules/consola/dist/shared/consola.4bbae468.cjs:585
    const isBadge = logObj.badge ?? logObj.level < 2;
                                  ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/jacob/Work/support-docs/system76/docs/node_modules/@nuxt/utils/node_modules/consola/dist/index.cjs:5:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

If I remove that `??`, I get an error for the next one being used. This is with node `v12.22.9` and npm `7.20.5`.

**Comment by jacobgkau** [comment]
Too clarify, this is preventing me from building locally to test PRs.

**Comment by jacobgkau** [comment]
To clarify, this is preventing me from building locally to test PRs.

**Comment by jacobgkau** [comment]
Looks like this might be the issue: https://github.com/unjs/consola/issues/222

**Comment by jacobgkau** [comment]
My system has nodejs 12, which is the version packaged by Ubuntu for jammy. Our readme says `14 <=` is required. I wonder if 14 would behave better than 12? (It's going to be difficult to install 14, since it's EOL.)

**Comment by jacobgkau** [comment]
Looking into the babel side of things, I found that our dependency `babel-eslint` was deprecated, the specific 10.x version we depend on has also been specifically deprecated (leaving 9.x as the latest normal release of that), and it's been replaced by `@babel/eslint-parser`. However, switching over to the latest version of that didn't help.

I guess I'll try installing nodejs 20, which is the latest LTS release.

**Comment by jacobgkau** [comment]
nodejs 20 was basically going to require updating all of the dependencies. I found a script to install the long-EOL nodejs 14, and it actually works.

I'll close this for now, but we're going to need to update the whole repo at some point since we're depending on a lot of EOL stuff right now.
